#############################################################################
# Makefile for building: Darqoin_new
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  Darqoin_new.pro
# Template: subdirs
# Command: C:\Qt\5.10.1\msvc2015_64\bin\qmake.exe -o Makefile Darqoin_new.pro "CONFIG+=debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.10.1\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.10.1\msvc2015_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.10.1\msvc2015_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-helpers \
		sub-models \
		sub-controllers


sub-helpers-qmake_all:  FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && $(MAKE) -f Makefile qmake_all
sub-helpers: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-helpers-make_first-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-helpers-make_first: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-helpers-all-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-helpers-all: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-helpers-clean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-helpers-clean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-helpers-distclean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-helpers-distclean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-helpers-install_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-helpers-install_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-helpers-uninstall_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-helpers-uninstall_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-models-qmake_all: sub-helpers-qmake_all FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && $(MAKE) -f Makefile qmake_all
sub-models: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-models-make_first-ordered: sub-helpers-make_first-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-models-make_first: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-models-all-ordered: sub-helpers-all-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-models-all: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-models-clean-ordered: sub-helpers-clean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-models-clean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-models-distclean-ordered: sub-helpers-distclean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-models-distclean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-models-install_subtargets-ordered: sub-helpers-install_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-models-install_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-models-uninstall_subtargets-ordered: sub-helpers-uninstall_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-models-uninstall_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-controllers-qmake_all: sub-models-qmake_all FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && $(MAKE) -f Makefile qmake_all
sub-controllers: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-controllers-make_first-ordered: sub-models-make_first-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-controllers-make_first: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-controllers-all-ordered: sub-models-all-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-controllers-all: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-controllers-clean-ordered: sub-models-clean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-controllers-clean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-controllers-distclean-ordered: sub-models-distclean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-controllers-distclean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-controllers-install_subtargets-ordered: sub-models-install_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-controllers-install_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-controllers-uninstall_subtargets-ordered: sub-models-uninstall_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-controllers-uninstall_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Darqoin_new.pro C:\Qt\5.10.1\msvc2015_64\mkspecs\win32-msvc\qmake.conf C:\Qt\5.10.1\msvc2015_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\common\angle.conf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\qconfig.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\common\msvc-version.conf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\toolchain.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\default_post.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qmake_use.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\file_copies.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\yacc.prf \
		C:\Qt\5.10.1\msvc2015_64\mkspecs\features\lex.prf \
		Darqoin_new.pro
	$(QMAKE) -o Makefile Darqoin_new.pro "CONFIG+=debug"
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\common\angle.conf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\qconfig.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qt_config.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\common\msvc-version.conf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\toolchain.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\default_pre.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\default_post.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\warn_on.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\qmake_use.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\file_copies.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\exceptions.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\yacc.prf:
C:\Qt\5.10.1\msvc2015_64\mkspecs\features\lex.prf:
Darqoin_new.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Darqoin_new.pro "CONFIG+=debug"

qmake_all: sub-helpers-qmake_all sub-models-qmake_all sub-controllers-qmake_all FORCE

make_first: sub-helpers-make_first-ordered sub-models-make_first-ordered sub-controllers-make_first-ordered  FORCE
all: sub-helpers-all-ordered sub-models-all-ordered sub-controllers-all-ordered  FORCE
clean: sub-helpers-clean-ordered sub-models-clean-ordered sub-controllers-clean-ordered  FORCE
distclean: sub-helpers-distclean-ordered sub-models-distclean-ordered sub-controllers-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-helpers-install_subtargets-ordered sub-models-install_subtargets-ordered sub-controllers-install_subtargets-ordered FORCE
uninstall_subtargets: sub-helpers-uninstall_subtargets-ordered sub-models-uninstall_subtargets-ordered sub-controllers-uninstall_subtargets-ordered FORCE

sub-helpers-debug_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
sub-models-debug_ordered: sub-helpers-debug_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
sub-controllers-debug_ordered: sub-models-debug_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
debug: sub-helpers-debug_ordered sub-models-debug_ordered sub-controllers-debug_ordered

sub-helpers-release_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
sub-models-release_ordered: sub-helpers-release_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
sub-controllers-release_ordered: sub-models-release_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
release: sub-helpers-release_ordered sub-models-release_ordered sub-controllers-release_ordered

sub-helpers-check_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
sub-models-check_ordered: sub-helpers-check_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
sub-controllers-check_ordered: sub-models-check_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
check: sub-helpers-check_ordered sub-models-check_ordered sub-controllers-check_ordered

sub-helpers-benchmark_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
sub-models-benchmark_ordered: sub-helpers-benchmark_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
sub-controllers-benchmark_ordered: sub-models-benchmark_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\aydar\Desktop\github\DarqoinMessenger\Darqoin_new\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-helpers-benchmark_ordered sub-models-benchmark_ordered sub-controllers-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

